# serverless.yml
component: website # (必填) 引用 component 的名称，当前用到的是 tencent-website 组件
name: tinablog # (必填) 该 website 组件创建的实例名称
app: tinablogApp # (可选) 该 website 应用名称
stage: prod # (可选) 用于区分环境信息，默认值是 dev

inputs:
  src:
    #src: ./public
    index: index.html
    error: index.html
    dist: ./public
    hook: npm run build
    # websitePath: ./
  region: ap-guangzhou
  bucketName: my-hexo-bucket
  protocol: https
  #cdn
  hosts:
    - host: blog.tinafang.com
      async: true
      area: mainland
      autoRefresh: true
      onlyRefresh: false
      https:
        switch: on
        http2: on
        certInfo:
          certId: 'haMhGlIc'